// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvhkdedzcisppknwfrmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2aGtkZWR6Y2lzcHBrbndmcm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTY3MzUsImV4cCI6MjA2MDgzMjczNX0.WzBBCt58tuSNSGdC6wjvlX9ifPBR7T0W1gODn3R5lmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);